# Form implementation generated from reading ui file 'Forms/form_teste_saida.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormTesteSaida(object):
    def setupUi(self, FormTesteSaida):
        FormTesteSaida.setObjectName("FormTesteSaida")
        FormTesteSaida.resize(480, 320)
        self.btVoltar = QtWidgets.QPushButton(parent=FormTesteSaida)
        self.btVoltar.setGeometry(QtCore.QRect(350, 240, 113, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btVoltar.setFont(font)
        self.btVoltar.setObjectName("btVoltar")
        self.ckCanaA = QtWidgets.QCheckBox(parent=FormTesteSaida)
        self.ckCanaA.setGeometry(QtCore.QRect(10, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ckCanaA.setFont(font)
        self.ckCanaA.setObjectName("ckCanaA")
        self.ckCanaB = QtWidgets.QCheckBox(parent=FormTesteSaida)
        self.ckCanaB.setGeometry(QtCore.QRect(130, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ckCanaB.setFont(font)
        self.ckCanaB.setObjectName("ckCanaB")
        self.ckCanaC = QtWidgets.QCheckBox(parent=FormTesteSaida)
        self.ckCanaC.setGeometry(QtCore.QRect(250, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ckCanaC.setFont(font)
        self.ckCanaC.setObjectName("ckCanaC")
        self.ckCanaD = QtWidgets.QCheckBox(parent=FormTesteSaida)
        self.ckCanaD.setGeometry(QtCore.QRect(370, 20, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ckCanaD.setFont(font)
        self.ckCanaD.setObjectName("ckCanaD")
        self.bt1 = QtWidgets.QPushButton(parent=FormTesteSaida)
        self.bt1.setGeometry(QtCore.QRect(10, 110, 84, 84))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt1.setFont(font)
        self.bt1.setObjectName("bt1")
        self.bt2 = QtWidgets.QPushButton(parent=FormTesteSaida)
        self.bt2.setGeometry(QtCore.QRect(130, 110, 84, 84))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt2.setFont(font)
        self.bt2.setObjectName("bt2")
        self.bt3 = QtWidgets.QPushButton(parent=FormTesteSaida)
        self.bt3.setGeometry(QtCore.QRect(250, 110, 84, 84))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt3.setFont(font)
        self.bt3.setObjectName("bt3")
        self.bt4 = QtWidgets.QPushButton(parent=FormTesteSaida)
        self.bt4.setGeometry(QtCore.QRect(370, 110, 84, 84))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.bt4.setFont(font)
        self.bt4.setObjectName("bt4")

        self.retranslateUi(FormTesteSaida)
        QtCore.QMetaObject.connectSlotsByName(FormTesteSaida)

    def retranslateUi(self, FormTesteSaida):
        _translate = QtCore.QCoreApplication.translate
        FormTesteSaida.setWindowTitle(_translate("FormTesteSaida", "Teste Saídas"))
        self.btVoltar.setText(_translate("FormTesteSaida", "Voltar"))
        self.ckCanaA.setToolTip(_translate("FormTesteSaida", "<html><head/><body><p><span style=\" font-size:24pt;\">Canal A</span></p></body></html>"))
        self.ckCanaA.setText(_translate("FormTesteSaida", "Canal A"))
        self.ckCanaB.setToolTip(_translate("FormTesteSaida", "<html><head/><body><p><span style=\" font-size:24pt;\">Canal A</span></p></body></html>"))
        self.ckCanaB.setText(_translate("FormTesteSaida", "Canal B"))
        self.ckCanaC.setToolTip(_translate("FormTesteSaida", "<html><head/><body><p><span style=\" font-size:24pt;\">Canal A</span></p></body></html>"))
        self.ckCanaC.setText(_translate("FormTesteSaida", "Canal C"))
        self.ckCanaD.setToolTip(_translate("FormTesteSaida", "<html><head/><body><p><span style=\" font-size:24pt;\">Canal A</span></p></body></html>"))
        self.ckCanaD.setText(_translate("FormTesteSaida", "Canal D"))
        self.bt1.setText(_translate("FormTesteSaida", "1"))
        self.bt2.setText(_translate("FormTesteSaida", "2"))
        self.bt3.setText(_translate("FormTesteSaida", "3"))
        self.bt4.setText(_translate("FormTesteSaida", "4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormTesteSaida = QtWidgets.QWidget()
    ui = Ui_FormTesteSaida()
    ui.setupUi(FormTesteSaida)
    FormTesteSaida.show()
    sys.exit(app.exec())
