# Form implementation generated from reading ui file 'Forms/form_menu_configurar.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormTesteSaida(object):
    def setupUi(self, FormTesteSaida):
        FormTesteSaida.setObjectName("FormTesteSaida")
        FormTesteSaida.resize(480, 320)
        self.btVoltar = QtWidgets.QPushButton(parent=FormTesteSaida)
        self.btVoltar.setGeometry(QtCore.QRect(190, 250, 113, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btVoltar.setFont(font)
        self.btVoltar.setObjectName("btVoltar")
        self.btCanal_A_Posi = QtWidgets.QPushButton(parent=FormTesteSaida)
        self.btCanal_A_Posi.setGeometry(QtCore.QRect(20, 0, 440, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btCanal_A_Posi.setFont(font)
        self.btCanal_A_Posi.setObjectName("btCanal_A_Posi")
        self.btCanal_B_Neg = QtWidgets.QPushButton(parent=FormTesteSaida)
        self.btCanal_B_Neg.setGeometry(QtCore.QRect(20, 60, 440, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btCanal_B_Neg.setFont(font)
        self.btCanal_B_Neg.setObjectName("btCanal_B_Neg")
        self.btCanal_C_Rele = QtWidgets.QPushButton(parent=FormTesteSaida)
        self.btCanal_C_Rele.setGeometry(QtCore.QRect(20, 120, 440, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btCanal_C_Rele.setFont(font)
        self.btCanal_C_Rele.setObjectName("btCanal_C_Rele")
        self.btCanal_D_PWM = QtWidgets.QPushButton(parent=FormTesteSaida)
        self.btCanal_D_PWM.setGeometry(QtCore.QRect(20, 180, 440, 70))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btCanal_D_PWM.setFont(font)
        self.btCanal_D_PWM.setObjectName("btCanal_D_PWM")

        self.retranslateUi(FormTesteSaida)
        QtCore.QMetaObject.connectSlotsByName(FormTesteSaida)

    def retranslateUi(self, FormTesteSaida):
        _translate = QtCore.QCoreApplication.translate
        FormTesteSaida.setWindowTitle(_translate("FormTesteSaida", "Form"))
        self.btVoltar.setText(_translate("FormTesteSaida", "Voltar"))
        self.btCanal_A_Posi.setToolTip(_translate("FormTesteSaida", "<html><head/><body><p align=\"justify\">CANAL A</p></body></html>"))
        self.btCanal_A_Posi.setText(_translate("FormTesteSaida", "CANAL A POSITIVO"))
        self.btCanal_B_Neg.setText(_translate("FormTesteSaida", "CANAL B NEGATIVO"))
        self.btCanal_C_Rele.setText(_translate("FormTesteSaida", "CANAL C RELÉ"))
        self.btCanal_D_PWM.setText(_translate("FormTesteSaida", "CANAL D PWM"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormTesteSaida = QtWidgets.QWidget()
    ui = Ui_FormTesteSaida()
    ui.setupUi(FormTesteSaida)
    FormTesteSaida.show()
    sys.exit(app.exec())
