# Form implementation generated from reading ui file 'Forms/form_configuracao_saidas.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_FormConfiguracaoSaidas(object):
    def setupUi(self, FormConfiguracaoSaidas):
        FormConfiguracaoSaidas.setObjectName("FormConfiguracaoSaidas")
        FormConfiguracaoSaidas.resize(480, 320)
        self.btVoltar = QtWidgets.QPushButton(parent=FormConfiguracaoSaidas)
        self.btVoltar.setGeometry(QtCore.QRect(20, 240, 124, 64))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btVoltar.setFont(font)
        self.btVoltar.setObjectName("btVoltar")
        self.btSalvar = QtWidgets.QPushButton(parent=FormConfiguracaoSaidas)
        self.btSalvar.setGeometry(QtCore.QRect(340, 240, 124, 64))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.btSalvar.setFont(font)
        self.btSalvar.setObjectName("btSalvar")
        self.lbTon = QtWidgets.QLabel(parent=FormConfiguracaoSaidas)
        self.lbTon.setGeometry(QtCore.QRect(100, 80, 120, 64))
        self.lbTon.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.lbTon.setText("")
        self.lbTon.setObjectName("lbTon")
        self.lbToff = QtWidgets.QLabel(parent=FormConfiguracaoSaidas)
        self.lbToff.setGeometry(QtCore.QRect(250, 80, 120, 64))
        self.lbToff.setStyleSheet("background-color: rgb(193, 193, 193);")
        self.lbToff.setText("")
        self.lbToff.setObjectName("lbToff")
        self.btPlus = QtWidgets.QPushButton(parent=FormConfiguracaoSaidas)
        self.btPlus.setGeometry(QtCore.QRect(10, 81, 64, 64))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.btPlus.setFont(font)
        self.btPlus.setObjectName("btPlus")
        self.btMinus = QtWidgets.QPushButton(parent=FormConfiguracaoSaidas)
        self.btMinus.setGeometry(QtCore.QRect(400, 80, 64, 64))
        font = QtGui.QFont()
        font.setPointSize(36)
        self.btMinus.setFont(font)
        self.btMinus.setObjectName("btMinus")
        self.label_3 = QtWidgets.QLabel(parent=FormConfiguracaoSaidas)
        self.label_3.setGeometry(QtCore.QRect(0, 20, 472, 32))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label = QtWidgets.QLabel(parent=FormConfiguracaoSaidas)
        self.label.setGeometry(QtCore.QRect(140, 150, 60, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=FormConfiguracaoSaidas)
        self.label_2.setGeometry(QtCore.QRect(290, 150, 60, 16))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(FormConfiguracaoSaidas)
        QtCore.QMetaObject.connectSlotsByName(FormConfiguracaoSaidas)

    def retranslateUi(self, FormConfiguracaoSaidas):
        _translate = QtCore.QCoreApplication.translate
        FormConfiguracaoSaidas.setWindowTitle(_translate("FormConfiguracaoSaidas", "Configuração"))
        self.btVoltar.setText(_translate("FormConfiguracaoSaidas", "Voltar"))
        self.btSalvar.setText(_translate("FormConfiguracaoSaidas", "Salvar"))
        self.btPlus.setText(_translate("FormConfiguracaoSaidas", "+"))
        self.btMinus.setText(_translate("FormConfiguracaoSaidas", "-"))
        self.label_3.setText(_translate("FormConfiguracaoSaidas", "<html><head/><body><p align=\"center\">Canal X Saída N</p></body></html>"))
        self.label.setText(_translate("FormConfiguracaoSaidas", "T On"))
        self.label_2.setText(_translate("FormConfiguracaoSaidas", "T Off"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormConfiguracaoSaidas = QtWidgets.QWidget()
    ui = Ui_FormConfiguracaoSaidas()
    ui.setupUi(FormConfiguracaoSaidas)
    FormConfiguracaoSaidas.show()
    sys.exit(app.exec())
